In [4]:
import pandas as pd
from datetime import datetime as dt

df = pd.read_csv('clima_data.csv')
df.head()

,Jahr,Temperatur-Minimum(C),Temperatur-Mittelwert(C),Temperatur-Maximum(C),Bodentemperatur-Minimum(C),Sonnenstunden(h),Relative Luftfeuchtigkeit(%),Regen(mm),Niederschlagsform(num),Schnee(cm),Neuschnee(cm),Windgeschwindigkeit-Maximum(km/h),Windgeschwindigkeit-Mittelwert(km/h)
0,1948-01-01,-5.0,-1.8,0.8,-4.7,n/A,89,5.7,8,4,n/A,n/A,n/A
1,1948-01-02,-2.7,4.4,6.8,-2.5,n/A,95,3.3,1,8,n/A,n/A,n/A
2,1948-01-03,5.2,8.5,10.6,4.6,n/A,86,4,1,0,n/A,n/A,n/A
3,1948-01-04,6.6,10.2,11.5,4.7,n/A,83,0.2,1,0,n/A,n/A,n/A
4,1948-01-05,8.0,10.5,12.0,5.9,n/A,78,2,1,0,n/A,n/A,n/A

In [12]:
temp = []
yr = []

for pos, d in df.iterrows():
    temp.append(d["Temperatur-Mittelwert(C)"])
    yr.append(d["Jahr"])

In [ ]:
min = -20.0
i = 0
for pos, d in df.iterrows():
    if d["Temperatur-Minimum(C)"] < min:
        min = d["Temperatur-Minimum(C)"]
        i = pos
print(i)